spring:
  application:
    name: EMPLOYEE-SERVICE
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  config:
    import: configserver:http://localhost:8888
    fail-fast: true
    retry:
      initialInterval: 5000
      maxInterval: 10000
      multiplier: 2
      maxAttempts:  5



#tradeoff between availability and consistency
#Can set spring.config.import: optional:configserver:http://localhost:8888 to rety on boot
